<?php

/**
 * BaseHeaven
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Plants
 * @property Doctrine_Collection $Plant_Heaven
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getPlants()       Returns the current record's "Plants" collection
 * @method Doctrine_Collection getPlantHeaven()  Returns the current record's "Plant_Heaven" collection
 * @method Heaven              setName()         Sets the current record's "name" value
 * @method Heaven              setPlants()       Sets the current record's "Plants" collection
 * @method Heaven              setPlantHeaven()  Sets the current record's "Plant_Heaven" collection
 * 
 * @package    marina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHeaven extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('heaven');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Plant as Plants', array(
             'refClass' => 'Plant_Heaven',
             'local' => 'heaven_id',
             'foreign' => 'plant_id'));

        $this->hasMany('Plant_Heaven', array(
             'local' => 'id',
             'foreign' => 'heaven_id'));
    }
}