<?php

/**
 * BaseFertilizer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property float $price
 * @property Doctrine_Collection $Plant
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method float               getPrice() Returns the current record's "price" value
 * @method Doctrine_Collection getPlant() Returns the current record's "Plant" collection
 * @method Fertilizer          setName()  Sets the current record's "name" value
 * @method Fertilizer          setPrice() Sets the current record's "price" value
 * @method Fertilizer          setPlant() Sets the current record's "Plant" collection
 * 
 * @package    marina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFertilizer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fertilizer');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Plant', array(
             'local' => 'id',
             'foreign' => 'fertilizer_id'));
    }
}