<?php

/**
 * BaseGroundType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Field
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getField() Returns the current record's "Field" collection
 * @method GroundType          setName()  Sets the current record's "name" value
 * @method GroundType          setField() Sets the current record's "Field" collection
 * 
 * @package    marina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroundType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ground_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Field', array(
             'local' => 'id',
             'foreign' => 'ground_type_id'));
    }
}