<?php

/**
 * BaseField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $prev_plant_id
 * @property integer $width
 * @property integer $length
 * @property integer $ground_type_id
 * @property integer $heaven_id
 * @property Plant $Plant
 * @property GroundType $GroundType
 * @property Heaven $Heaven
 * 
 * @method string     getName()           Returns the current record's "name" value
 * @method integer    getPrevPlantId()    Returns the current record's "prev_plant_id" value
 * @method integer    getWidth()          Returns the current record's "width" value
 * @method integer    getLength()         Returns the current record's "length" value
 * @method integer    getGroundTypeId()   Returns the current record's "ground_type_id" value
 * @method integer    getHeavenId()       Returns the current record's "heaven_id" value
 * @method Plant      getPlant()          Returns the current record's "Plant" value
 * @method GroundType getGroundType()     Returns the current record's "GroundType" value
 * @method Heaven     getHeaven()         Returns the current record's "Heaven" value
 * @method Field      setName()           Sets the current record's "name" value
 * @method Field      setPrevPlantId()    Sets the current record's "prev_plant_id" value
 * @method Field      setWidth()          Sets the current record's "width" value
 * @method Field      setLength()         Sets the current record's "length" value
 * @method Field      setGroundTypeId()   Sets the current record's "ground_type_id" value
 * @method Field      setHeavenId()       Sets the current record's "heaven_id" value
 * @method Field      setPlant()          Sets the current record's "Plant" value
 * @method Field      setGroundType()     Sets the current record's "GroundType" value
 * @method Field      setHeaven()         Sets the current record's "Heaven" value
 * 
 * @package    marina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('field');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('prev_plant_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('length', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ground_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('heaven_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Plant', array(
             'local' => 'prev_plant_id',
             'foreign' => 'id'));

        $this->hasOne('GroundType', array(
             'local' => 'ground_type_id',
             'foreign' => 'id'));

        $this->hasOne('Heaven', array(
             'local' => 'heaven_id',
             'foreign' => 'id'));
    }
}