<?php

/**
 * BasePlant_Heaven
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $plant_id
 * @property integer $heaven_id
 * @property Plant $Plant
 * @property Heaven $Heaven
 * 
 * @method integer      getPlantId()   Returns the current record's "plant_id" value
 * @method integer      getHeavenId()  Returns the current record's "heaven_id" value
 * @method Plant        getPlant()     Returns the current record's "Plant" value
 * @method Heaven       getHeaven()    Returns the current record's "Heaven" value
 * @method Plant_Heaven setPlantId()   Sets the current record's "plant_id" value
 * @method Plant_Heaven setHeavenId()  Sets the current record's "heaven_id" value
 * @method Plant_Heaven setPlant()     Sets the current record's "Plant" value
 * @method Plant_Heaven setHeaven()    Sets the current record's "Heaven" value
 * 
 * @package    marina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlant_Heaven extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plant__heaven');
        $this->hasColumn('plant_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('heaven_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Plant', array(
             'local' => 'plant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Heaven', array(
             'local' => 'heaven_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}