<?php

/**
 * FertilizerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FertilizerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FertilizerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fertilizer');
    }

    public static function getAll()
    {
        return Doctrine_Query::create()
            ->select("f.*")
            ->from('Fertilizer f')
            ;
    }
}