<?php

/**
 * FieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Field');
    }

    public static function getAll()
    {
        return Doctrine_Query::create()
            ->select("f.*")
            //->select("f.*, p.name as plant_name")
            ->from('Field f')
            //->leftJoin("f.Plant p")
        ;

    }

}