<?php

/**
 * GroundTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework

class GroundTypeTable extends Doctrine_Table
{

    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroundType');
    }

    public static function findById($id)
    {
        return Doctrine_Query::create()
            ->from('GroundType g')
            ->where('g.id = ?', $id)
            ->fetchOne()
            ;
    }

    public static function getAll()
    {
        return Doctrine_Query::create()
            ->select("g.*")
            ->from('Ground g')
            ->orderBy('g.id desc')
            ;
    }

    public static function getNextsById($id)
    {
        return Doctrine_Query::create()
            ->select("g.*, n.value as value")
            ->from('GroundType g')
            ->leftJoin("g.Grounds n")
            ->where('n.ground_type_id = ?', $id)
            ->orderBy('n.value desc')
            ;
    }



}*/



/**
 * GroundTypeTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroundTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroundTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroundType');
    }

    public static function findById($id)
    {
        return Doctrine_Query::create()
            ->from('GroundType g')
            ->where('g.id = ?', $id)
            ->fetchOne()
            ;
    }

    public static function getAll()
   {
        return Doctrine_Query::create()
            ->select("g.*")
            ->from('GroundType g')
            ;
   }

}