<?php

/**
 * GroundTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroundTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroundTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroundType');
    }

    public static function findById($id)
    {
        return Doctrine_Query::create()
            ->from('GroundType g')
            ->where('g.id = ?', $id)
            ->fetchOne()
            ;
    }

}