<?php

/**
 * Heaven
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    marina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Heaven extends BaseHeaven
{
    public function __toString(){
        return (string)$this->getName();
    }

    public function getNextPlantsHeavenMap()
    {
        $result = new SplObjectStorage();

        $nexts = PlantTable::getAll()->execute();
        foreach($nexts as $next){
            $result[$next] = 1;
        }

        $nexts = PlantTable::getHeavensById($this->getId())->execute();
        foreach($nexts as $next){
            $result[$next] =  10;
        }
        return $result;
    }

}
