<?php

/**
 * Plant_GroundTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Plant_GroundTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Plant_GroundTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plant_Ground');
    }

}