<?php

/**
 * PlantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object PlantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plant');
    }

    public static function getAll()
    {
        return Doctrine_Query::create()
            ->select("p.*")
            ->from('Plant p')
            ->orderBy('p.price desc')
            ;
    }

    public static function getNextsById($id)
    {
        return Doctrine_Query::create()
            ->select("p.*, n.value as value")
            ->from('Plant p')
            ->leftJoin("p.PrevPR n")
            ->where('n.prev_plant_id = ?', $id)
            ->orderBy('n.value desc')
            ;
    }
    public static function findPlant($id)
    {
        return Doctrine_Query::create()
            ->from('Plant p')
            ->where('p.id = ?', $id)
            ->fetchOne()
            ;
    }
    public static function getGroundTypesById($id)
{
    return Doctrine_Query::create()
        ->select("p.*")
        ->from('Plant p')
        ->leftJoin("p.Plant_Ground n")
        ->where('n.ground_id= ?', $id)
        ;
}
    public static function getHeavensById($id)
    {
        return Doctrine_Query::create()
            ->select("p.*")
            ->from('Plant p')
            ->leftJoin("p.Plant_Heaven n")
            ->where('n.heaven_id= ?', $id)
            ;
    }

}