<?php

/**
 * Plant_HeavenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Plant_HeavenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Plant_HeavenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plant_Heaven');
    }
}