<?php

/**
 * PlantRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlantRelation');
    }
}