<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('field', 'field_ground_type_id_ground_type_id');
        $this->createForeignKey('field', 'field_ground_type_id_fertilizer_id', array(
             'name' => 'field_ground_type_id_fertilizer_id',
             'local' => 'ground_type_id',
             'foreign' => 'id',
             'foreignTable' => 'fertilizer',
             ));
        $this->addIndex('field', 'field_ground_type_id', array(
             'fields' => 
             array(
              0 => 'ground_type_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('field', 'field_ground_type_id_ground_type_id', array(
             'name' => 'field_ground_type_id_ground_type_id',
             'local' => 'ground_type_id',
             'foreign' => 'id',
             'foreignTable' => 'ground_type',
             ));
        $this->dropForeignKey('field', 'field_ground_type_id_fertilizer_id');
        $this->removeIndex('field', 'field_ground_type_id', array(
             'fields' => 
             array(
              0 => 'ground_type_id',
             ),
             ));
    }
}