<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('field', 'width');
        $this->removeColumn('field', 'length');
    }

    public function down()
    {
        $this->addColumn('field', 'width', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('field', 'length', 'integer', '8', array(
             'notnull' => '1',
             ));
    }
}